post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 15.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end
end

use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'15.0'

target 'MKNearbyInteraction_Example' do
  pod 'MKNearbyInteraction', :path => '../'
  
  pod 'SDCycleScrollView','>= 1.82'
  
  pod 'MLInputDodger'
  
  pod 'SVGKit'
  
  pod 'SYNoticeBrowseLabel'
  
  pod 'MKBaseModuleLibrary'
  
  pod 'MKCustomUIModule'
  
  
  
end
