post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 16.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      end
    end
  end
end

use_frameworks!
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios,'16.0'

target 'MKNearbyInteraction_Example' do
  pod 'MKNearbyInteraction', :path => '../'
end
