use_frameworks!

platform :ios, '10.0'

target 'MKNearbyInteraction_Example' do
  pod 'MKNearbyInteraction', :path => '../'

  target 'MKNearbyInteraction_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
